version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: iricshkin/django-stripe-project:v01.11
    restart: always
    volumes:
      - static_value:/app/static/:rw
      - media_value:/app/media/:rw
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/usr/share/nginx/html/tatic/:ro
      - media_value:/usr/share/nginx/html/media:ro
    depends_on:
      - web
    env_file:
      - ./.env

volumes:
  postgres_data:
  static_value:
  media_value:
