# Generated by Django 4.1.3 on 2022-11-19 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название скиди"),
                ),
                (
                    "amount",
                    models.FloatField(
                        max_length=25,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="Размер скидки",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PERCENTAGE", "percentage"), ("FIXED", "fixed")],
                        default="PERCENTAGE",
                        max_length=32,
                        verbose_name="Тип скидки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discount",
                "verbose_name_plural": "Discounts",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование товара"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.FloatField(
                        max_length=25,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "usd"), ("RUB", "rub")],
                        default="USD",
                        max_length=10,
                        verbose_name="Валюта товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название налога"),
                ),
                (
                    "percentage",
                    models.PositiveSmallIntegerField(
                        default=13, verbose_name="Процентная ставка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax",
                "verbose_name_plural": "Taxes",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stripecheckout.discount",
                        verbose_name="Скидка",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        to="stripecheckout.item", verbose_name="Список товаров"
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stripecheckout.tax",
                        verbose_name="Налог",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "default_related_name": "orders",
            },
        ),
    ]
