# Generated by Django 4.1.3 on 2022-11-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripecheckout", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="type",
            field=models.CharField(
                choices=[("PERCENTAGE", "percentage"), ("FIXED", "fixed")],
                default="percentage",
                max_length=32,
                verbose_name="Тип скидки",
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="percentage",
            field=models.PositiveSmallIntegerField(
                default=20, verbose_name="Процентная ставка"
            ),
        ),
    ]
