# Generated by Django 4.1.3 on 2022-11-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripecheckout", "0004_alter_item_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(
                choices=[("usd", "Доллары"), ("rub", "Рубли")],
                default="usd",
                max_length=10,
                verbose_name="Валюта заказа",
            ),
        ),
    ]
